<a href="https://colab.research.google.com/github/navgaur/AWP/blob/main/1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Analytics / Computing with Python**



(SEC-16 Course offered by Physics, DU)

---

## **Unit-II**

*Pandas: Working with Data Frame, Importing fromExcel or .csv files, Powerful filters and indexes. Numpy: Selecting data with loc and iloc, Using NumPy for speed, Trade-offs between arrays and lists, Array functions. Data cleansing and normalization: Libraries for data visualization, Types of charts/graphs and how to build them.*

### **Dataframe**: It is a two dimensional labeled data-structure to store, manipulate data in a tabular form.

In [ ]:
import pandas as pd
data = {
    'Name': ["Apple", "Orange", "Grapes", "Banana"],
    'Quantity': [11, 22, 17, 5],
    'Country' : ["India", "China", "US", "Australia"]
}

df=pd.DataFrame(data)
print(df)

     Name  Quantity    Country
0   Apple        11      India
1  Orange        22      China
2  Grapes        17         US
3  Banana         5  Australia

df1.head()  :  First 5 rows of the data file

df1.tail()  :  Last 5 rows of the data file

df1.info()  :  structure of the data file

df1.describe() : statistics

df1.shape() : (rows, columnns)

df1.columns() : column names

In [ ]:
# Reading csv raw file from github

import pandas as pd

url='https://raw.githubusercontent.com/navgaur/AWP/main/data.csv'

df1=pd.read_csv(url)
#print(df1.tail())
#print(df1.info())
#print(df1.describe())
print(df1.columns)

Index(['Index', 'Customer Id', 'First Name', 'Last Name', 'Company', 'City',
       'Country', 'Phone 1', 'Phone 2', 'Email', 'Subscription Date',
       'Website'],
      dtype='object')

In [ ]:
df1["First Name"]

0       Sheryl
1      Preston
2          Roy
3        Linda
4       Joanna
        ...
95        Karl
96        Lynn
97        Fred
98      Yvonne
99    Clarence
Name: First Name, Length: 100, dtype: object

In [ ]:
df1.iloc[0]

Index                                         1
Customer Id                     DD37Cf93aecA6Dc
First Name                               Sheryl
Last Name                                Baxter
Company                         Rasmussen Group
City                               East Leonard
Country                                   Chile
Phone 1                            229.077.5154
Phone 2                        397.884.0519x718
Email                  zunigavanessa@smith.info
Subscription Date                    2020-08-24
Website              http://www.stephenson.com/
Name: 0, dtype: object

In [ ]:
# Reading excel raw file from github

import pandas as pd

url='https://raw.githubusercontent.com/navgaur/AWP/main/data.xls'

df2=pd.read_excel(url)
print(df2.tail())
print(df2.info())
print(df2.columns)

   0 First Name Last Name  Gender        Country  Age        Date    Id
4  5    Nereida   Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston     Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta      Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean    Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza   Weiland  Female  United States   40  21/05/2015  6548
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   0           9 non-null      int64
 1   First Name  9 non-null      object
 2   Last Name   9 non-null      object
 3   Gender      9 non-null      object
 4   Country     9 non-null      object
 5   Age         9 non-null      int64
 6   Date        9 non-null      object
 7   Id          9 non-null      int64
dtypes: int64(3), object(5)
memory usage: 708.0+ bytes
None
Index([0, 'First Name', 'Last Name', 'Gender', 'Country', 'Age', 'Date', 'Id'], dtype='object')

***iloc* and *loc*.**

*iloc*: index based selection df.iloc[row_index, colmn_index]

*loc*: label based selection df.iloc[row_label, colmn_label]

In [ ]:
df2.iloc[2:6,1:4]

  First Name Last Name  Gender
2     Philip      Gent    Male
3   Kathleen    Hanner  Female
4    Nereida   Magwood  Female
5     Gaston     Brumm    Male

In [ ]:
df2.loc[1:3,"Gender"]

1    Female
2      Male
3    Female
Name: Gender, dtype: object

In [ ]:
df2.loc[df2["Age"] > 50]

   0 First Name Last Name  Gender        Country  Age        Date    Id
4  5    Nereida   Magwood  Female  United States   58  16/08/2016  2468
6  7       Etta      Hurn  Female  Great Britain   56  15/10/2017  3598

### **List vs Array**

List
- Built in
- Mixed data type allowed
- Slow

Array (numpy)
-  same data type
- much faster
- use less memory

**Mathematical Functions**

*np.add(arr,n), np.multiply(arr,n), np.divide(arr,n),np.power(arr,n), np.sqrt(a),np.sin(a), np.cos(a)*

**Array functions**

*np.sum(a), np.mean(a), np.min(a), np.max(a), np.median(a), np.std(a), np.var(a)*

**Sorting and Searching**

*np.sort(a), *



*arr.flatten(), arr.reshape(row,colum)*

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
print(np.zeros(5))
print(np.ones(3))
np.full(4,7)

print(np.arange(1,10,2))     # arange(start, end, step)
print(np.linspace(0,10,5))   # linspace(start, end, no of points)
a1 = a.reshape(2,3)
print(a1)
print(a1.flatten())

[0. 0. 0. 0. 0.]
[1. 1. 1.]
[1 3 5 7 9]
[ 0.   2.5  5.   7.5 10. ]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]

In [ ]:
arr1=np.array([[2,8,5],[1,0,5],[4,7,1]])
print(np.sum(arr1, axis=0))
print(np.sum(arr1, axis=1))
arr2=arr1.flatten()
print(arr2)
print(np.sort(arr2))
print(np.where(arr2 > 3, 1, 2))

[ 7 15 11]
[15  6 12]
[2 8 5 1 0 5 4 7 1]
[0 1 1 2 4 5 5 7 8]
[2 1 1 2 2 1 1 1 2]

## **Data Cleansing and normalization**

These steps are required for a data to be made ready for Machine Learning

*Data Cleansing:* Is to fix or remove incorrect, incomplete or messy data

*Data normalization:* This (also called scaling) is done to normalize the data so that no particular feature dominates.

In [9]:
import pandas as pd

data1 = {"Name" :["Deepak", "Param", "Sanjiv","David", "Jatin", None, "Sanjiv"],
         "Age" :[ 25, None, 30.2, 28, 52, 110, 30],
         "Salary" :[50000, 20000, None, 30000, 55000, 80000, None],
         "City" : ["Delhi", "delhi", "Mumbai", "Bangalore", "Bomday", "Pune", "Mumbai"]}

df3=pd.DataFrame(data1)
print(df3)

df31=df3
print(df31)

     Name    Age   Salary       City
0  Deepak   25.0  50000.0      Delhi
1   Param    NaN  20000.0      delhi
2  Sanjiv   30.2      NaN     Mumbai
3   David   28.0  30000.0  Bangalore
4   Jatin   52.0  55000.0     Bomday
5    None  110.0  80000.0       Pune
6  Sanjiv   30.0      NaN     Mumbai
     Name    Age   Salary       City
0  Deepak   25.0  50000.0      Delhi
1   Param    NaN  20000.0      delhi
2  Sanjiv   30.2      NaN     Mumbai
3   David   28.0  30000.0  Bangalore
4   Jatin   52.0  55000.0     Bomday
5    None  110.0  80000.0       Pune
6  Sanjiv   30.0      NaN     Mumbai

### **Data Cleansing**

Problems with data are :
- Missing values : some cells are empty
- Duplicates : some rows are repeated
- Wrong format : say "4" is written instead of 4.
- Outliers : For example Age is given to be 1000
- inconsistent : for example in city Delhi, DElhi, delhi are written.


The option **inplace** (by default **False**) is made to be **True** then it removes the desired things from the database.

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      float64
 2   Salary  5 non-null      float64
 3   City    6 non-null      object
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

In [ ]:
df3.isnull().sum()         # Counts Null per column

df3.dropna()               # Drops rows with null entries

df3.dropna(subset=["Name", "Salary"])  # Drops the rows if specific columns have null entries

     Name   Age   Salary       City
0  Deepak  25.0  50000.0      Delhi
1   Param   NaN  20000.0      delhi
3   David  28.0  30000.0  Bangalore
4   Jatin  52.0  55000.0     Bomday

In [ ]:
df3.fillna(0)       # Fill 0 where there is missing or null values

     Name    Age   Salary       City
0  Deepak   25.0  50000.0      Delhi
1   Param    0.0  20000.0      delhi
2  Sanjiv   30.0      0.0     Mumbai
3   David   28.0  30000.0  Bangalore
4   Jatin   52.0  55000.0     Bomday
5       0  110.0  80000.0       Pune

In [ ]:
df3["Age"].fillna(df3["Age"].mean())

0     25.0
1     49.0
2     30.0
3     28.0
4     52.0
5    110.0
Name: Age, dtype: float64

In [8]:
df31.drop_duplicates(inplace=True) # The duplicate rows will be deleted in df31
df31

     Name    Age   Salary       City
0  Deepak   25.0  50000.0      Delhi
1   Param    NaN  20000.0      delhi
2  Sanjiv   30.0      NaN     Mumbai
3   David   28.0  30000.0  Bangalore
4   Jatin   52.0  55000.0     Bomday
5    None  110.0  80000.0       Pune

In [15]:
df31.dropna(inplace=True)                  # This won't change the df31 whereas if "inplace = True" the rows with wrong entries will be deleted in df31

In [18]:
# Fixing data-type

df31["Age"] = df31["Age"].astype(int)      #

In [17]:
df31

     Name  Age   Salary       City
0  Deepak   25  50000.0      Delhi
3   David   28  30000.0  Bangalore
4   Jatin   52  55000.0     Bomday

In [21]:
# Standardizing text

df31["City"] = df31["City"].str.upper()

In [22]:
df31

     Name  Age   Salary       City
0  Deepak   25  50000.0      DELHI
3   David   28  30000.0  BANGALORE
4   Jatin   52  55000.0     BOMDAY